import os
import ConfigParser

PROJECT_ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

CONFIG_FILE_NAME = "properties.ini"

CONFIG_FILE_PATH = PROJECT_ROOT_DIR + "/" + CONFIG_FILE_NAME

config = ConfigParser.ConfigParser()
config.read(CONFIG_FILE_PATH)

STANFORD_DEP_PARSER_HOME = PROJECT_ROOT_DIR + "/" + config.get("STANFORD_DEP_PARSER", "PARSER_HOME")

STANFORD_NER_MODEL = PROJECT_ROOT_DIR + "/" + config.get("STANFORD_NER", "PARSER_MODEL")
STANFORD_NER_JAR = PROJECT_ROOT_DIR + "/" + config.get("STANFORD_NER", "PARSER_JAR")

GLOVE_EMBEDDINGS = PROJECT_ROOT_DIR + "/" + config.get("GLOVE_EMBEDDINGS", "EMBEDDINGS_PATH")

TOKENIZER_PATH = PROJECT_ROOT_DIR + "/" + config.get("TOKENIZER", "TOKENIZER_PATH")

AMR_ALIGNMENTS_SPLIT = PROJECT_ROOT_DIR + "/" + config.get("AMR_ALIGNMENTS", "SPLIT")
AMR_ALIGNMENTS_UNSPLIT = PROJECT_ROOT_DIR + "/" + config.get("AMR_ALIGNMENTS", "UNSPLIT")

CONCEPTS_RELATIONS_DICT = PROJECT_ROOT_DIR + "/" + config.get("CONCEPTS_RELATIONS", "DICT_PATH")